### ISSUE TITLE
parsing 101: dreamland

### ISSUE THREAD

**Issue by sesprit** [Daltix/Exercises#2]
Complete the parsing 101 exercise.
Make sure you have read the wiki first.
You can ask questions via comments on this issue.
Don't forget to branch of develop and create a pull-request when you are done.

Add these URLs to the URL's list:

https://www.dreamland.be/e/nl/dl/luchtmatras-voor-1-persoon-lachend-kakske-124700
https://www.dreamland.be/e/nl/dl/banzai-wip-water-totter-124616
https://www.dreamland.be/e/nl/dl/waterpistool-minions-124712

Note: in case any of the URLs leads to a 404 pick a new product URL (post as comment on this issue which one).

**Comment by Nicolas225** [comment]
Beste,
Hoe moet de originele prijs berekend worden van een product? Al de Dreamland producten hebben geen promotie en ik heb de html gecheckt van producten in promotie en deze bezitten ook geen originele prijs of discount prijs. Misschien heb ik erover gekeken of is het de bedoeling discounts obv volledige bestellingen in rekening te brengen? 
Met vriendelijke groeten,
Nicolas Daelemans

**Comment by Nicolas225** [comment]
Beste Simon,


Ik heb reeds een comment gepost op Github ivm de originele prijs dat ik niet weet hoe ik deze moet berekenen. Geen van de Dreamland-producten die ik moet beschouwen hebben een promotie, en andere producten in promotie hebben ook geen specifieke prijs van wat de originele prijs of discount-prijs zou zijn.

Daarnaast had ik nog enkele vragen ivm de volledige opdracht. Hoe moet ik met de breakpoints werken in het eindresultaat? Of is het gewoon in orde dat ik het uiteindelijke resultaat upload op Github zonder meer? Ten tweede weet ik ook niet goed hoe ik de virtual environment moet interpreteren als bijdrage voor dit project.


Met vriendelijke groeten,

Nicolas Daelemans


________________________________

**Comment by sesprit** [comment]
Dag Nicolas,
als er geen originele prijs beschikbaar is hoef je deze niet te gaan berekenen. Doel van de oefening is om puur info uit de html te halen die beschikbaar is, je hoeft er geen bij te berekenen. Lost dit je vraag op?

**Comment by Nicolas225** [comment]
Ja ik denk het wel! 
Bedankt!
