### ISSUE TITLE
parsing 101: lidl

### ISSUE THREAD

**Issue by sesprit** [Daltix/Exercises#4]
Complete the parsing 101 exercise.
Make sure you have read the wiki first.
You can ask questions via comments on this issue.
Don't forget to branch of develop and create a pull-request when you are done.

Add these URLs to the URL's list:

https://www.lidl-shop.be/nl-BE/PARKSIDE-Cirkelzaagblad/p100197506
https://www.lidl-shop.be/nl-BE/ESMARA-Longshirt-voor-dames/p100214261
https://www.lidl-shop.be/nl-BE/LIVARNOLIVING-Spiegelkast/p100211942

Note: in case any of the URLs leads to a 404 pick a new product URL (post as comment on this issue which one).

**Comment by cdnhaese** [comment]
@sesprit Since only a screenshot of Gamma's online shop is given in the exercises folder, is it also the meaning to implement the "extract_categories" function for this assignment?
