### ISSUE TITLE
parsing 101: coolblue

### ISSUE THREAD

**Issue by sesprit** [Daltix/Exercises#6]
Complete the parsing 101 exercise.
Make sure you have read the wiki first.
You can ask questions via comments on this issue.
Don't forget to branch of develop and create a pull-request when you are done.

Add these URLs to the URL's list:

https://www.haardrogershop.be/product/568136/category-203968/philips-bhd176-00.html
https://www.pdashop.be/product/705719/apple-iphone-se-64-gb-zilver.html
https://www.wasmachinestore.be/product/774207/haier-hw70-bp14636.html

Note: in case any of the URLs leads to a 404 pick a new product URL (post as comment on this issue which one).

**Comment by thomashlvt** [comment]
I have a problem with the extract_categories function. On the Coolblue website the categories are 'hidden' in a dropdown menu, wich causes the catogories only to show in the html file after clicking the dropdown menu. (f. ex. when I load the first URL and immediately after check the html source via Chrome, the 'Huishouden' category doesn't show, but after I click the dropdown menu and then click 'inspect' I do find it (through Ctrl+F 'Huishouden')). Is there any way around this?

**Comment by sesprit** [comment]
@thomashlvt well spotted,
indeed these are loaded using javascript.
You can ignore these for this exercise and return the links next to the product, like the ones underneath Keuzehulp.
